/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface Config {
  admin: Addr;
  code_ids: CodeIds;
}
export interface CodeIds {
  campaign: number;
  cw20: number;
  cw3: number;
  receipt: number;
}
export type ExecuteMsg = {
  create_campaign: {
    expiration: number;
    goal: Coin;
    name: string;
    recipient: string;
  };
} | {
  update_config: {
    admin?: Addr | null;
    code_ids: CodeIds;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin?: string | null;
  code_ids: CodeIds;
}
export type QueryMsg = {
  get_config: {};
} | {
  get_campaigns: {
    limit?: number | null;
    start_after?: string | null;
  };
};