/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Campaign.types";
import * as _1 from "./Campaign.client";
import * as _2 from "./Factory.types";
import * as _3 from "./Factory.client";
import * as _4 from "./Receipt.types";
import * as _5 from "./Receipt.client";
export namespace contracts {
  export const Campaign = { ..._0,
    ..._1
  };
  export const Factory = { ..._2,
    ..._3
  };
  export const Receipt = { ..._4,
    ..._5
  };
}