/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsgForMetadata = {
  mint: MintMsgForMetadata;
} | {
  update_metadata: {
    amount: Uint128;
    token_id: string;
  };
} | {
  burn: {
    token_id: string;
  };
};
export type Uint128 = string;
export interface MintMsgForMetadata {
  extension: Metadata;
  owner: string;
  token_id: string;
  token_uri?: string | null;
}
export interface Metadata {
  payments: Payment[];
  total: Uint128;
  [k: string]: unknown;
}
export interface Payment {
  amount: Uint128;
  date: number;
}
export interface InstantiateMsg {
  minter: string;
  name: string;
  symbol: string;
}